CREATE TABLE IF NOT EXISTS user (
  ID INTEGER IDENTITY PRIMARY KEY,
  EMAIL VARCHAR(45) NOT NULL,
  FIRST_NAME VARCHAR(45) NOT NULL,
  IS_BLOCKED BOOLEAN NOT NULL,
  LAST_NAME VARCHAR(45) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL);

CREATE TABLE IF NOT EXISTS security_role (
  ID INTEGER IDENTITY PRIMARY KEY,
  NAME VARCHAR(45) NOT NULL);

CREATE TABLE IF NOT EXISTS user_security_ref (
  USER_ID INTEGER NOT NULL,
  SECURITY_ROLE_ID INTEGER NOT NULL,
  PRIMARY KEY (USER_ID, SECURITY_ROLE_ID),
  FOREIGN KEY (SECURITY_ROLE_ID) REFERENCES security_role(ID),
  FOREIGN KEY (USER_ID) REFERENCES user(ID));

CREATE TABLE IF NOT EXISTS transport (
  ID INTEGER IDENTITY PRIMARY KEY,
  NAME VARCHAR(45) NOT NULL);

CREATE TABLE IF NOT EXISTS country (
  ID INTEGER IDENTITY PRIMARY KEY,
  NAME VARCHAR(45) NOT NULL);

CREATE TABLE IF NOT EXISTS route_point (
  ID INTEGER IDENTITY PRIMARY KEY,
  IS_BLOCKED BOOLEAN NOT NULL,
  NAME VARCHAR(45) NOT NULL,
  COUNTRY_ID INTEGER NOT NULL,
  FOREIGN KEY (COUNTRY_ID) REFERENCES country(ID));

CREATE TABLE IF NOT EXISTS route_connection (
  ID INTEGER IDENTITY PRIMARY KEY,
  IS_BLOCKED BOOLEAN NOT NULL,
  PRICE INTEGER NOT NULL,
  "TIME" INTEGER NOT NULL,
  route_point_a_id INTEGER NOT NULL,
  route_point_b_id INTEGER NOT NULL,
  transport_id INTEGER NOT NULL,
  FOREIGN KEY (route_point_b_id) REFERENCES route_point(ID),
  FOREIGN KEY (route_point_a_id) REFERENCES route_point(ID),
  FOREIGN KEY (transport_id) REFERENCES transport(ID));

CREATE TABLE IF NOT EXISTS saved_route (
  ID INTEGER IDENTITY PRIMARY KEY,
  IS_COMPANY_ROUTE BOOLEAN NOT NULL,
  MODIFICATION_TIME DATE NOT NULL,
  NAME VARCHAR(45) NOT NULL,
  USER_ID INTEGER NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES user(ID));

CREATE TABLE IF NOT EXISTS route (
  SEQUENCE_NUMBER INTEGER NOT NULL,
  SAVED_ROUTE_ID INTEGER NOT NULL,
  ROUTE_CONNECTION_ID INTEGER NOT NULL,
  PRIMARY KEY (SAVED_ROUTE_ID, ROUTE_CONNECTION_ID),
  FOREIGN KEY (ROUTE_CONNECTION_ID) REFERENCES route_connection(ID),
  FOREIGN KEY (SAVED_ROUTE_ID) REFERENCES saved_route(ID));